<a href="https://colab.research.google.com/github/cce15/GoldVison/blob/main/robotArmFrames.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
""" Kinematic chain of a robot arm (planar)
    Assignment
"""

' Kinematic chain of a robot arm (planar)\n    Assignment \n'


![](https://github.com/eraldoribeiro/assignment_robotarm2D/blob/main/robotArm01.png?raw=1)
*Figure 1*: A two-dimensional articulated arm. The articulated structure has 3 local coordinate frames each one centered at a joint. For each part, the local x-axis is aligned with the part.  

Consider the arm structure shown in Figure 1. Assume the following values for the arm configuration:
- The location of the first joint (i.e., the one that is attached to the ground support) is ${\bf p}_1 = \left(3,2\right)^\mathsf{T}$.
- The lengths of the parts are $L_1 = 5$ and  $L_2 = 8$.

In [1]:
import numpy as np
import math as mph

### Question 1

Write the matrices that represent the local coordinate frames $\mathcal F\{1\}$, $\mathcal F\{2\}$, and $\mathcal F\{3\}$. These frames are indicated in green in Figure 1. The transformation matrices you need to write are $T_{0,1}$, $T_{1,2}$, and $T_{2,3}$.

In [14]:
# Answer goes here. Add more code/markdown cells as needed
phi_0=0
phi_1= np.pi/8
phi_2= np.pi/4
phi_3=0



T01= np.array([[np.cos(phi_1),-np.sin(phi_1),3]
               ,[np.sin(phi_1),np.cos(phi_1),2],
                [0            ,0            ,1]])

L1=5
print(f"T01 {T01}")
T12= np.array([[np.cos(phi_2),-np.sin(phi_2),L1]
               ,[np.sin(phi_2),np.cos(phi_2),0],
                [0            ,0            ,1]])
print(f"T12 {T12}")

L2=8
T23= np.array([[np.cos(phi_3),-np.sin(phi_3),L2]
               ,[np.sin(phi_3),np.cos(phi_3),0],
                [0            ,0            ,1]])
print(f"T23 {T23}")

T01 [[ 0.92387953 -0.38268343  3.        ]
 [ 0.38268343  0.92387953  2.        ]
 [ 0.          0.          1.        ]]
T12 [[ 0.70710678 -0.70710678  5.        ]
 [ 0.70710678  0.70710678  0.        ]
 [ 0.          0.          1.        ]]
T23 [[ 1. -0.  8.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [10]:
# point writen w.r.t Fram1
p= np.array([0,0,1])

In [11]:
# point written w.r.t fram 0 (Global frame)
p_0= T01 @ p
print(p_0)

[3. 2. 1.]


### Question 2

Write the matrices that represent each local frame w.r.t. the global frame $\mathcal F\{0\}$. The transformations you need to write are $T_{0,1}$, $T_{0,2}$, and $T_{0,3}$.

In [ ]:
# Answer goes here. Add more code/markdown cells as needed




### Question 3

Write the matrices that represent the local coordinate frames $\mathcal F\{1\}$, $\mathcal F\{2\}$, and $\mathcal F\{3\}$. These frames are indicated in green in Figure 1. The transformation matrices you need to write are $T_{0,1}$, $T_{1,2}$, and $T_{2,3}$.

In [ ]:
# Answer goes here. Add more code/markdown cells as needed




### Question 4

Using the transformations from the previous questions, calculate the global coordinates of the middle point of each part of the robot arm when $\phi_1 = \pi/8$ and $\phi_2 = \pi/4$. Hint: the location of the middle point of part 1 is $(\frac{L_1}{2},0)^\mathsf{T}$ (w.r.t. frame $\mathcal F\{1\}$).

In [ ]:
# Answer goes here. Add more code/markdown cells as needed






### Question 5

Using the transformations from the previous questions, calculate the global coordinates of all the joint points and the end-effector location when $\phi_1 = \pi/4$ and $\phi_2 = \pi/8$.

In [ ]:
# Answer goes here. Add more code/markdown cells as needed





### Question 6

Write the matrix that represents the coordinate frame of the end effector w.r.t. frame  $\mathcal F\{1\}$, i.e., $T_{1,3}$

In [ ]:
# Answer goes here. Add more code/markdown cells as needed




### Question 7

Write the matrix that represents the coordinate frame $\mathcal F\{1\}$ w.r.t. to the frame of the end effector

In [ ]:
# Answer goes here. Add more code/markdown cells as needed


